services:
  mysql:
    image: mariadb:10.11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurm-network

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  slurmrestd:
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmrestd"]
    container_name: slurmrestd
    hostname: slurmrestd
    user: slurmrestd
    environment:
      SLURM_JWT: "1"
      SLURMRESTD_LISTEN: "0.0.0.0:6820"
      SLURMRESTD_DEBUG: "9"
      SLURMRESTD_JSON: "pretty"
      SLURMRESTD_SECURITY: "disable_unshare_sysv,disable_unshare_files"
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6820"
    ports:
      - 6820:6820
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  c2:
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

networks:
  slurm-network:
    driver: bridge
